//
// Generated file, do not edit! Created by opp_msgtool 6.1 from SRMessage.msg.
//

#ifndef __SRMESSAGE_M_H
#define __SRMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SRMessage;
/**
 * Enum generated from <tt>SRMessage.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * enum SRFrameType
 * {
 *     DATA_FRAME = 0;
 *     ACK_FRAME = 1;
 *     NAK_FRAME = 2;
 * }
 * </pre>
 */
enum SRFrameType {
    DATA_FRAME = 0,
    ACK_FRAME = 1,
    NAK_FRAME = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SRFrameType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SRFrameType& e) { int n; b->unpack(n); e = static_cast<SRFrameType>(n); }

/**
 * Class generated from <tt>SRMessage.msg:20</tt> by opp_msgtool.
 * <pre>
 * packet SRMessage
 * {
 *     int type;
 *     int seqNum;
 *     int ackNum;
 *     string payload;
 * }
 * </pre>
 */
class SRMessage : public ::omnetpp::cPacket
{
  protected:
    int type = 0;
    int seqNum = 0;
    int ackNum = 0;
    omnetpp::opp_string payload;

  private:
    void copy(const SRMessage& other);

  protected:
    bool operator==(const SRMessage&) = delete;

  public:
    SRMessage(const char *name=nullptr, short kind=0);
    SRMessage(const SRMessage& other);
    virtual ~SRMessage();
    SRMessage& operator=(const SRMessage& other);
    virtual SRMessage *dup() const override {return new SRMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual int getAckNum() const;
    virtual void setAckNum(int ackNum);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SRMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SRMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SRMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<SRMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SRMESSAGE_M_H

